framework:
    default_locale: 'en'
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - 'en'
            - 'fr'
        enabled: true
        cache_dir: '%kernel.cache_dir%/translations'
