# config/services.yaml
parameters:
    # Define your parameters here
    blog_image_directory: '%kernel.project_dir%/public/uploads/blogs'

services:
    # Default configuration for all services
    _defaults:
        autowire: true      # Automatically injects dependencies
        autoconfigure: true # Automatically registers services

    # Makes classes in src/ available as services
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # Explicit service definitions
    Symfony\Component\Finder\Finder: ~

    # Image uploader service with parameter injection
    App\Service\ImageUploader:
        arguments:
            $targetDirectory: '%blog_image_directory%'
            $slugger: '@Symfony\Component\String\Slugger\SluggerInterface'


            parameters:
    env(DEEP_TRANSLATE_API_KEY): ''
    env(DEEP_TRANSLATE_API_HOST): ''

    App\Service\DeepTranslateService:
        arguments:
            $apiKey: '%env(54c18af5b6mshf7f78a660ff45fep1c79e3jsn5327daf7875c)%'
            $apiHost: '%env(deep-translate1.p.rapidapi.com)%'