<?php

namespace ContainerX74Z7Mk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_USmVlGbService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.uSmVlGb' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.uSmVlGb'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\CategorieController::delete' => ['privates', '.service_locator.aw9RHlF', 'get_ServiceLocator_Aw9RHlFService', true],
            'App\\Controller\\CategorieController::edit' => ['privates', '.service_locator.aw9RHlF', 'get_ServiceLocator_Aw9RHlFService', true],
            'App\\Controller\\CategorieController::index' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\CategorieController::new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\CategorieController::show' => ['privates', '.service_locator.j7wOkYK', 'get_ServiceLocator_J7wOkYKService', true],
            'App\\Controller\\ServiceController::delete' => ['privates', '.service_locator.0_8rZbK', 'get_ServiceLocator_08rZbKService', true],
            'App\\Controller\\ServiceController::edit' => ['privates', '.service_locator.0_8rZbK', 'get_ServiceLocator_08rZbKService', true],
            'App\\Controller\\ServiceController::index' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\ServiceController::new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\ServiceController::show' => ['privates', '.service_locator.1IRrkci', 'get_ServiceLocator_1IRrkciService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\CategorieController:delete' => ['privates', '.service_locator.aw9RHlF', 'get_ServiceLocator_Aw9RHlFService', true],
            'App\\Controller\\CategorieController:edit' => ['privates', '.service_locator.aw9RHlF', 'get_ServiceLocator_Aw9RHlFService', true],
            'App\\Controller\\CategorieController:index' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\CategorieController:new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\CategorieController:show' => ['privates', '.service_locator.j7wOkYK', 'get_ServiceLocator_J7wOkYKService', true],
            'App\\Controller\\ServiceController:delete' => ['privates', '.service_locator.0_8rZbK', 'get_ServiceLocator_08rZbKService', true],
            'App\\Controller\\ServiceController:edit' => ['privates', '.service_locator.0_8rZbK', 'get_ServiceLocator_08rZbKService', true],
            'App\\Controller\\ServiceController:index' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\ServiceController:new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\ServiceController:show' => ['privates', '.service_locator.1IRrkci', 'get_ServiceLocator_1IRrkciService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\CategorieController::delete' => '?',
            'App\\Controller\\CategorieController::edit' => '?',
            'App\\Controller\\CategorieController::index' => '?',
            'App\\Controller\\CategorieController::new' => '?',
            'App\\Controller\\CategorieController::show' => '?',
            'App\\Controller\\ServiceController::delete' => '?',
            'App\\Controller\\ServiceController::edit' => '?',
            'App\\Controller\\ServiceController::index' => '?',
            'App\\Controller\\ServiceController::new' => '?',
            'App\\Controller\\ServiceController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\CategorieController:delete' => '?',
            'App\\Controller\\CategorieController:edit' => '?',
            'App\\Controller\\CategorieController:index' => '?',
            'App\\Controller\\CategorieController:new' => '?',
            'App\\Controller\\CategorieController:show' => '?',
            'App\\Controller\\ServiceController:delete' => '?',
            'App\\Controller\\ServiceController:edit' => '?',
            'App\\Controller\\ServiceController:index' => '?',
            'App\\Controller\\ServiceController:new' => '?',
            'App\\Controller\\ServiceController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
