<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOd2Unwj\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOd2Unwj/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOd2Unwj.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOd2Unwj\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOd2Unwj\App_KernelDevDebugContainer([
    'container.build_hash' => 'Od2Unwj',
    'container.build_id' => 'c5e62ad2',
    'container.build_time' => 1744582997,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOd2Unwj');
